import '@/libs/ui/globals.css';

import Sidebar from '@/libs/ui/components/sidebar';
import { ToastProvider } from '@/libs/ui/components/providers/toaster-provider';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body
      className={
        'flex w-screen lg:flex-row flex-col min-h-screen overflow-x-hidden scrollbar-thin scrollbar-thumb-gray-900 scrollbar-track-gray-100'
      }
    >
      <ToastProvider />
      <Sidebar />
      <div className="flex-1 w-full px-6 py-8 lg:border-l-2">{children}</div>
    </body>
  );
}
