import '@/libs/ui/globals.css';

import Sidebar from '@/libs/ui/components/sidebar';
import toast, { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body
      className={
        'flex w-screen lg:flex-row flex-col min-h-screen overflow-x-hidden scrollbar-thin scrollbar-thumb-gray-900 scrollbar-track-gray-100 '
      }
    >
      <Sidebar />

      <main className="flex-1 w-full lg:px-6 lg:py-8  px-3 py-2 lg:border-l-2 bg-gray-100">
        {children}
      </main>
      <Toaster
        position="bottom-right"
        reverseOrder={false}
        toastOptions={{
          // Define default options
          className: '',
          duration: 5000,
          style: {
            background: 'white',
            color: 'black',
          },
        }}
      />
    </body>
  );
}
